name: Shared Variables

on:
  workflow_call:

jobs:
  shared-variables:
    runs-on: ubuntu-latest
    outputs:
      default-nodejs-version: ${{ steps.set-vars.outputs.default-nodejs-version }}
      matrix-nodejs-pm: ${{ steps.set-vars.outputs.matrix-nodejs-pm }}
      default-python-version: ${{ steps.set-vars.outputs.default-python-version }}
      default-checkov-version: ${{ steps.set-vars.outputs.default-checkov-version }}
    steps:
      - name: Set shared variables
        id: set-vars
        run: |
          echo "default-nodejs-version=22" >> $GITHUB_OUTPUT
          echo "matrix-nodejs-pm=['npm', 'yarn', 'pnpm']" >> $GITHUB_OUTPUT
          echo "default-python-version=3.12" >> $GITHUB_OUTPUT
          echo "default-checkov-version=3.2.414" >> $GITHUB_OUTPUT